<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" href="/css/enderstudy.css" />
    <link rel="stylesheet" href="/css/authorisation.css" />
    <?= $this->headTitle('Enderstudy OAuth')->setSeparator(' - ')->setAutoEscape(false) ?>
</head>
<body>
    <div class="col-12 authorisation-prompt d-flex flex-column">
        <div class="header d-flex">
            <div class="col-6">
                <img src="/img/LogoFulltext.svg" />
            </div>
            <div class="col-6 text-right">
                <span class="text-info text-uppercase">authorisation prompt</span>
            </div>
        </div>
        <div class="content d-flex flex-column">
            <div class="row d-flex mb-3">
                <div class="col-12 d-flex justify-content-center text-center">
                    <h1>Already Authorised</h1>
                </div>
                <div class="col-12 d-flex justify-content-center mt-3">
                    <img class="img-circle img-fluid border-danger mr-1" src="https://i.pravatar.cc/300" />
                    <img class="img-circle img-fluid border-info ml-1" src="https://i.pravatar.cc/300" />
                </div>
            </div>
            <hr>
            <div class="row d-flex mt-3">
                <div class="col-12 d-flex justify-content-center mb-1">
                    <h5>
                        You have already authorised <span class="text-danger"><?= $this->application->getName() ?>"</span>
                        to access your account.
                    </h5>
                </div>
                <div class="col-12 d-flex justify-content-center mb-1">
                    <p class="text-center">Don't remember authorising this app? You can remove it's access by visiting the <br>
                    <a href="#" class="text-info">"Apps" section of your dashboard</a></p>
                </div>
                <hr>
                <div class="col-12 d-flex justify-content-center mb-1">
                    <p>Otherwise you can close this window/tab, no further action is needed</p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>
