<div class="row text-center">
    <div class="col-sm-8 col-sm-offset-2">
        <h2>An application is trying to access your account</h2>
        <div class="col-sm-12">
            <p>The app identifying itself as <b><?= $this->application->getName() ?></b>
                is a third party application not developed by Enderstudy,<br>
                please excercise caution when allowing third party apps to access your account</p>
            <p>Some details about this application;</p>
            <ul>
                <li><?= $this->application->getUsers()->count() ?> Users</li>
                <li>Registered <?= $this->application->getDateCreated()->format('d/m/Y H:i:s') ?></li>
            </ul>
        </div>
        <div class="col-sm-12">
            <a href="<?= $this->url('oauth/consent-granted', [], [
                    'query' => ['client_id' => $this->application->getClientId()]
            ]) ?>" class="btn btn-warning">Allow</a>
            <a class="btn btn-primary">Deny</a>
        </div>
    </div>
</div>
