<h1>Register an application</h1>
<?php
    $form = $this->form;
    $form->prepare();
?>

<?= $this->form()->openTag($form); ?>

<div class="form-group">
    <?= $this->formLabel($form->get('name')); ?>
    <?= $this->formElement($form->get('name')); ?>
</div>
<div class="form-group">
    <?= $this->formLabel($form->get('description')); ?>
    <?= $this->formElement($form->get('description')); ?>
</div>

<?= $this->formElement($form->get('submit')); ?>
<?= $this->form()->closeTag(); ?>
