<?php
    $this->headTitle('Sign up');
    $form = $this->form;
?>

<div class="row">
    <div class="col-sm-12">
        <h2>Sign up</h2>
        <?= $this->form()->openTag($form) ?>
        <div class="form-group">
            <?= $this->formLabel($form->get('username')); ?>
            <?= $this->formElement($form->get('username')); ?>
            <?= $this->formElementErrors($form->get('username')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('first_name')); ?>
            <?= $this->formElement($form->get('first_name')); ?>
            <?= $this->formElementErrors($form->get('first_name')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('last_name')); ?>
            <?= $this->formElement($form->get('last_name')); ?>
            <?= $this->formElementErrors($form->get('last_name')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('password')); ?>
            <?= $this->formElement($form->get('password')); ?>
            <?= $this->formElementErrors($form->get('password')); ?>
        </div>
        <div class="form-group">
            <?= $this->formLabel($form->get('date_of_birth')); ?>
            <?= $this->formElement($form->get('date_of_birth')); ?>
            <?= $this->formElementErrors($form->get('date_of_birth')); ?>
        </div>
        <div class="form-group">
            <?= $this->formElement($form->get('submit')); ?>
        </div>
    </div>
</div>
